In [59]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
def relu(x):
    return x * (x > 0)

In [70]:
N1, N2 = 4, 5
epochs, sigma = 10, .05

In [63]:
# load data
X, y = datasets.load_boston(return_X_y=True)
[n, dim] = X.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25)

In [64]:
[n_train, dim] = X_train.shape

In [51]:
n, dim

(506, 13)

In [81]:
# init weights
W1 = np.random.rand(dim + 1, N1) - .5
W2 = np.random.rand(N1 + 1, N2) - .5
w = np.random.rand(N2 + 1) - .5

In [82]:
for i in range(epochs):
    A1 = relu(np.matmul(np.column_stack([X_train, np.ones(n_train)]), W1))
    A2 = relu(np.matmul(np.column_stack([A1, np.ones(n_train)]), W2))
    y_hat = np.matmul(np.column_stack([A2, np.ones(n_train)]), w)
    loss = np.dot(y_hat - y_train, y_hat - y_train)
    print('Epoch = ' + str(i) + ', loss = ' + str(loss))
    
    # update weights
    w -= sigma * 2 * np.matmul((y_hat - y_train), np.column_stack([A2, np.ones(n_train)]))
    

Epoch = 0, loss = 200019.96895612974
Epoch = 1, loss = 18729781480449.145
Epoch = 2, loss = 8.807114226460125e+21
Epoch = 3, loss = 5.462694286168855e+30
Epoch = 4, loss = 3.448452119093589e+39
Epoch = 5, loss = 2.1789922030049207e+48
Epoch = 6, loss = 1.3769221120239068e+57
Epoch = 7, loss = 8.700901739286377e+65
Epoch = 8, loss = 5.498183343503983e+74
Epoch = 9, loss = 3.474354868394791e+83


In [86]:
np.matmul(np.column_stack([A1, np.ones(n_train)]), W2)


array([[ -4.36212843, -16.05591048,  11.69342471,  -8.61008027,
         12.00923503],
       [ 11.59899879, -39.20748115,  20.34016556,  -6.87668078,
          0.33258947],
       [ -3.58140684, -14.00536339,   9.61127391,  -5.57723926,
          9.06868392],
       ...,
       [ 31.66368877, -65.79030122,  30.57458711,  -6.66420706,
        -13.48524655],
       [ 24.55724147, -59.53261212,  28.801789  ,  -7.6451707 ,
         -7.52560272],
       [ 37.16494481, -71.77873687,  32.61811585,  -6.23305285,
        -17.71252993]])

In [72]:
A2.shape

(303, 5)

In [56]:
A2

array([[45.33223016, -0.        , 91.5193904 , -0.        , 15.44282654],
       [44.28679445, -0.        , 88.5093751 , -0.        , 14.91081784],
       [43.77333243, -0.        , 87.48771595, -0.        , 14.7379454 ],
       ...,
       [44.05301906, -0.        , 88.04422138, -0.        , 14.83211032],
       [43.66489707, -0.        , 87.27195709, -0.        , 14.70143738],
       [44.04329206, -0.        , 88.02486712, -0.        , 14.82883544]])

In [58]:
y_hat

array([-16.96404904, -16.46835961, -16.28169287, -16.49039572,
       -16.6081123 , -16.467592  , -16.49020766, -16.58638466,
       -16.21533956, -16.05103391, -16.39397891, -16.51871401,
       -16.36357427, -16.32222457, -15.43043449, -16.27375846,
       -15.8803895 , -15.85782567, -10.92096479, -16.04589904,
       -15.39040459, -16.11880195, -16.42756792, -16.2886776 ,
       -16.23373039, -11.59683185, -15.32005894, -11.76703412,
       -15.8633118 , -15.48459544, -14.58956499, -15.27128168,
        -8.18982748, -14.44566234,  -8.83315371, -16.49372365,
       -15.72399856, -16.48877952, -16.37589824, -18.3712859 ,
       -18.36238889, -15.99749446, -15.90345324, -16.37671028,
       -16.16305964, -16.4838879 , -16.53179414, -16.36813065,
       -16.6424003 , -16.50515291, -16.95142671, -16.83269525,
       -16.95030981, -16.96970957, -16.27905257, -18.73798623,
       -18.63216377, -18.77593068, -16.74661755, -17.0266911 ,
       -16.97063933, -16.28342842, -16.99262042, -16.98